export const LIMITS = {
  MAX_BOTS_TOTAL: 500,
  MAX_BOTS_PER_WORKER: 100,
  MAX_WORKERS: 10,
  MAX_USERNAME_LENGTH: 32,
  MIN_PASSWORD_LENGTH: 6,
  MAX_PASSWORD_LENGTH: 128,
  MAX_CONFIG_NAME_LENGTH: 64,
  MAX_JVM_ARGS: 50,
  MAX_SERVER_ARGS: 20,
  AUDIT_PAGE_SIZE_DEFAULT: 20,
  AUDIT_PAGE_SIZE_MAX: 100,
} as const;
